Interactions work well

diff --git a/bin/run-visualizer b/bin/run-visualizer
--- a/bin/run-visualizer
+++ b/bin/run-visualizer
@@ -16,4 +16,8 @@ export DEBUG=1
 export PUBLIC_URL="/"
 
 compose up --detach --force-recreate --build $@
-compose logs -f
+if [ $? -eq 0 ]; then
+  compose logs -f
+else
+  echo "Error starting containers"
+fi
diff --git a/tagging-app/bin/run-debug b/tagging-app/bin/run-debug
--- a/tagging-app/bin/run-debug
+++ b/tagging-app/bin/run-debug
@@ -12,4 +12,8 @@ export IMAGES_TO_TAG="./tagging-app/_data/pipeline_output/images"
 export PIPELINE_OUTPUT="./tagging-app/_data/pipeline_output"
 
 docker-compose -f docker-compose.tagging.yml up --force-recreate --detach --build $@
-docker-compose -f docker-compose.tagging.yml logs -f
+if [ $? -eq 0 ]; then
+  docker-compose -f docker-compose.tagging.yml logs -f
+else
+  echo "Error starting containers"
+fi
